// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Renats_BE.Data;

#nullable disable

namespace Renats_BE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609025949_AddLogTypeAndImageUrlToTrackingLogs")]
    partial class AddLogTypeAndImageUrlToTrackingLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Renats_BE.Models.BatchBid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<decimal>("BidPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("bid_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("factory_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("FactoryId");

                    b.ToTable("batch_bids", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.BatchImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("batch_images", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.BatchOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcceptedBidId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_bid_id");

                    b.Property<decimal>("AgreedPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("agreed_price");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("factory_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedBidId");

                    b.HasIndex("BatchId")
                        .IsUnique();

                    b.HasIndex("FactoryId");

                    b.ToTable("batch_orders", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.Depot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_person");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province");

                    b.Property<int>("ReputationScore")
                        .HasColumnType("integer")
                        .HasColumnName("reputation_score");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tax_code");

                    b.Property<int>("TotalTransactions")
                        .HasColumnType("integer")
                        .HasColumnName("total_transactions");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("depots", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("license_number");

                    b.Property<decimal?>("MaxCapacityKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("max_capacity_kg");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VehiclePlate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vehicle_plate");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.Factory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcceptedMaterialTypes")
                        .HasColumnType("text")
                        .HasColumnName("accepted_material_types");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("BusinessLicenseUrl")
                        .HasColumnType("text")
                        .HasColumnName("business_license_url");

                    b.Property<decimal?>("CapacityPerMonthTon")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("capacity_per_month_ton");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_person");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EnvironmentLicenseUrl")
                        .HasColumnType("text")
                        .HasColumnName("environment_license_url");

                    b.Property<string>("IndustrialZone")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("industrial_zone");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("is_premium");

                    b.Property<bool>("IsProfileComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_profile_complete");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<decimal?>("MinPurityRequired")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("min_purity_required");

                    b.Property<DateTime?>("PremiumExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("premium_expires_at");

                    b.Property<string>("PrimaryMaterialType")
                        .HasColumnType("text")
                        .HasColumnName("primary_material_type");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tax_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("factories", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.InventoryBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("accepted_at");

                    b.Property<decimal?>("ActualWeightKg")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("actual_weight_kg");

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("batch_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("EstimatedWeightKg")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("estimated_weight_kg");

                    b.Property<DateTime?>("ListedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("listed_at");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("material_type");

                    b.Property<decimal?>("MoisturePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("moisture_percentage");

                    b.Property<decimal?>("PurityPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("purity_percentage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_image_url");

                    b.Property<string>("TransportType")
                        .HasColumnType("text")
                        .HasColumnName("transport_type");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("BatchCode")
                        .IsUnique();

                    b.HasIndex("DepotId");

                    b.HasIndex("MaterialType")
                        .HasDatabaseName("idx_batches_material");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_batches_status");

                    b.ToTable("inventory_batches", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_order_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InvoiceFileUrl")
                        .HasColumnType("text")
                        .HasColumnName("invoice_file_url");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("invoice_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal?>("Subtotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_amount");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.Property<decimal?>("VatAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("vat_amount");

                    b.HasKey("Id");

                    b.HasIndex("BatchOrderId")
                        .IsUnique();

                    b.HasIndex("UploadedBy");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_notifications_user");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.PickupRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedDepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_depot_id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pickup_address");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("pickup_date");

                    b.Property<string>("PickupSlot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pickup_slot");

                    b.Property<string>("RequestCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("request_code");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("WeighedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("weighed_at");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDepotId");

                    b.HasIndex("RequestCode")
                        .IsUnique();

                    b.HasIndex("SellerId")
                        .HasDatabaseName("idx_pickup_requests_seller");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_pickup_requests_status");

                    b.ToTable("pickup_requests", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.PickupRequestImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<Guid>("PickupRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_request_id");

                    b.HasKey("Id");

                    b.HasIndex("PickupRequestId");

                    b.ToTable("pickup_request_images", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.PickupRequestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MaterialEmoji")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("material_emoji");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_id");

                    b.Property<string>("MaterialLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("material_label");

                    b.Property<Guid>("PickupRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_request_id");

                    b.HasKey("Id");

                    b.HasIndex("PickupRequestId");

                    b.ToTable("pickup_request_items", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.PickupResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MaterialLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("material_label");

                    b.Property<Guid>("PickupRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_request_id");

                    b.Property<decimal>("PricePerKg")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("price_per_kg");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("PickupRequestId");

                    b.ToTable("pickup_results", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("average_rating");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<int>("CompletedRequests")
                        .HasColumnType("integer")
                        .HasColumnName("completed_requests");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultAddress")
                        .HasColumnType("text")
                        .HasColumnName("default_address");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province");

                    b.Property<int>("TotalRequests")
                        .HasColumnType("integer")
                        .HasColumnName("total_requests");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("sellers", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.TransportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_order_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveredTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delivered_time");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delivery_address");

                    b.Property<decimal?>("DeliveryLatitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("delivery_latitude");

                    b.Property<decimal?>("DeliveryLongitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("delivery_longitude");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<decimal?>("EstimatedDistanceKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("estimated_distance_km");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pickup_address");

                    b.Property<decimal?>("PickupLatitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("pickup_latitude");

                    b.Property<decimal?>("PickupLongitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("pickup_longitude");

                    b.Property<DateTime?>("PickupTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("pickup_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal?>("TransportFee")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("transport_fee");

                    b.HasKey("Id");

                    b.HasIndex("BatchOrderId")
                        .IsUnique();

                    b.HasIndex("DriverId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_transport_status");

                    b.ToTable("transport_jobs", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.TransportTrackingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<string>("LogType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("log_type");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("TransportJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_job_id");

                    b.HasKey("Id");

                    b.HasIndex("TransportJobId");

                    b.ToTable("transport_tracking_logs", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.WeightTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_order_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("GrossWeightKg")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("gross_weight_kg");

                    b.Property<decimal?>("NetWeightKg")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("net_weight_kg");

                    b.Property<decimal?>("TareWeightKg")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("tare_weight_kg");

                    b.Property<string>("TicketImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("ticket_image_url");

                    b.Property<string>("TicketNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ticket_number");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.Property<string>("WeighingStation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("weighing_station");

                    b.HasKey("Id");

                    b.HasIndex("BatchOrderId")
                        .IsUnique();

                    b.HasIndex("UploadedBy");

                    b.ToTable("weight_tickets", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.WeightVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_order_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DepotWeightKg")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("depot_weight_kg");

                    b.Property<decimal?>("DifferenceKg")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("difference_kg");

                    b.Property<decimal?>("DifferencePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("difference_percentage");

                    b.Property<decimal?>("FactoryWeightKg")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("factory_weight_kg");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("VerificationNote")
                        .HasColumnType("text")
                        .HasColumnName("verification_note");

                    b.HasKey("Id");

                    b.HasIndex("BatchOrderId")
                        .IsUnique();

                    b.ToTable("weight_verifications", (string)null);
                });

            modelBuilder.Entity("Renats_BE.Models.BatchBid", b =>
                {
                    b.HasOne("Renats_BE.Models.InventoryBatch", "Batch")
                        .WithMany("Bids")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renats_BE.Models.Factory", "Factory")
                        .WithMany("Bids")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("Renats_BE.Models.BatchImage", b =>
                {
                    b.HasOne("Renats_BE.Models.InventoryBatch", "Batch")
                        .WithMany("Images")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Renats_BE.Models.BatchOrder", b =>
                {
                    b.HasOne("Renats_BE.Models.BatchBid", "AcceptedBid")
                        .WithMany()
                        .HasForeignKey("AcceptedBidId");

                    b.HasOne("Renats_BE.Models.InventoryBatch", "Batch")
                        .WithOne("Order")
                        .HasForeignKey("Renats_BE.Models.BatchOrder", "BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renats_BE.Models.Factory", "Factory")
                        .WithMany("Orders")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcceptedBid");

                    b.Navigation("Batch");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("Renats_BE.Models.Depot", b =>
                {
                    b.HasOne("Renats_BE.Models.User", "User")
                        .WithOne("Depot")
                        .HasForeignKey("Renats_BE.Models.Depot", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Renats_BE.Models.Driver", b =>
                {
                    b.HasOne("Renats_BE.Models.User", "User")
                        .WithOne("Driver")
                        .HasForeignKey("Renats_BE.Models.Driver", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Renats_BE.Models.Factory", b =>
                {
                    b.HasOne("Renats_BE.Models.User", "User")
                        .WithOne("Factory")
                        .HasForeignKey("Renats_BE.Models.Factory", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Renats_BE.Models.InventoryBatch", b =>
                {
                    b.HasOne("Renats_BE.Models.Depot", "Depot")
                        .WithMany("Batches")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("Renats_BE.Models.Invoice", b =>
                {
                    b.HasOne("Renats_BE.Models.BatchOrder", "BatchOrder")
                        .WithOne("Invoice")
                        .HasForeignKey("Renats_BE.Models.Invoice", "BatchOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renats_BE.Models.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy");

                    b.Navigation("BatchOrder");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Renats_BE.Models.Notification", b =>
                {
                    b.HasOne("Renats_BE.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Renats_BE.Models.PickupRequest", b =>
                {
                    b.HasOne("Renats_BE.Models.Depot", "AssignedDepot")
                        .WithMany()
                        .HasForeignKey("AssignedDepotId");

                    b.HasOne("Renats_BE.Models.Seller", "Seller")
                        .WithMany("PickupRequests")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedDepot");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Renats_BE.Models.PickupRequestImage", b =>
                {
                    b.HasOne("Renats_BE.Models.PickupRequest", "PickupRequest")
                        .WithMany("Images")
                        .HasForeignKey("PickupRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PickupRequest");
                });

            modelBuilder.Entity("Renats_BE.Models.PickupRequestItem", b =>
                {
                    b.HasOne("Renats_BE.Models.PickupRequest", "PickupRequest")
                        .WithMany("Items")
                        .HasForeignKey("PickupRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PickupRequest");
                });

            modelBuilder.Entity("Renats_BE.Models.PickupResult", b =>
                {
                    b.HasOne("Renats_BE.Models.PickupRequest", "PickupRequest")
                        .WithMany("Results")
                        .HasForeignKey("PickupRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PickupRequest");
                });

            modelBuilder.Entity("Renats_BE.Models.Seller", b =>
                {
                    b.HasOne("Renats_BE.Models.User", "User")
                        .WithOne("Seller")
                        .HasForeignKey("Renats_BE.Models.Seller", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Renats_BE.Models.TransportJob", b =>
                {
                    b.HasOne("Renats_BE.Models.BatchOrder", "BatchOrder")
                        .WithOne("TransportJob")
                        .HasForeignKey("Renats_BE.Models.TransportJob", "BatchOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renats_BE.Models.Driver", "Driver")
                        .WithMany("TransportJobs")
                        .HasForeignKey("DriverId");

                    b.Navigation("BatchOrder");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Renats_BE.Models.TransportTrackingLog", b =>
                {
                    b.HasOne("Renats_BE.Models.TransportJob", "TransportJob")
                        .WithMany("TrackingLogs")
                        .HasForeignKey("TransportJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportJob");
                });

            modelBuilder.Entity("Renats_BE.Models.WeightTicket", b =>
                {
                    b.HasOne("Renats_BE.Models.BatchOrder", "BatchOrder")
                        .WithOne("WeightTicket")
                        .HasForeignKey("Renats_BE.Models.WeightTicket", "BatchOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renats_BE.Models.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy");

                    b.Navigation("BatchOrder");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Renats_BE.Models.WeightVerification", b =>
                {
                    b.HasOne("Renats_BE.Models.BatchOrder", "BatchOrder")
                        .WithOne("WeightVerification")
                        .HasForeignKey("Renats_BE.Models.WeightVerification", "BatchOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatchOrder");
                });

            modelBuilder.Entity("Renats_BE.Models.BatchOrder", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("TransportJob");

                    b.Navigation("WeightTicket");

                    b.Navigation("WeightVerification");
                });

            modelBuilder.Entity("Renats_BE.Models.Depot", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("Renats_BE.Models.Driver", b =>
                {
                    b.Navigation("TransportJobs");
                });

            modelBuilder.Entity("Renats_BE.Models.Factory", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Renats_BE.Models.InventoryBatch", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Images");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Renats_BE.Models.PickupRequest", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Items");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Renats_BE.Models.Seller", b =>
                {
                    b.Navigation("PickupRequests");
                });

            modelBuilder.Entity("Renats_BE.Models.TransportJob", b =>
                {
                    b.Navigation("TrackingLogs");
                });

            modelBuilder.Entity("Renats_BE.Models.User", b =>
                {
                    b.Navigation("Depot");

                    b.Navigation("Driver");

                    b.Navigation("Factory");

                    b.Navigation("Notifications");

                    b.Navigation("Seller");
                });
#pragma warning restore 612, 618
        }
    }
}
